//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public Cycle()
        {
            this.Subject = new HashSet<Subject>();
        }
    
        public int Cycle_ID { get; set; }
        public string CycleName { get; set; }
    
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
