//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Workload = new HashSet<Workload>();
        }
    
        public int Subject_ID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Cycle_ID { get; set; }
        public Nullable<double> HourseAmount { get; set; }
    
        public virtual Cycle Cycle { get; set; }
        public virtual ICollection<Workload> Workload { get; set; }
    }
}
