//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Workload = new HashSet<Workload>();
        }
    
        public int Teacher_ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartament { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Workload> Workload { get; set; }
    }
}
