//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workload
    {
        public int Workload_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
